### PR TITLE
Store completed input step state

### PR DESCRIPTION
**Pull request by i386**
@samrocketman hacking on this in my own time. Not sure if this is the right approach - WDYT?

### CODE REVIEW

**Comment by svanoort** [comment]
Not a good idea, necessarily -- Executions are not something you want to store indefinitely, potentially for safety/sanity concerns.  Better to attach the returned parameter values to the ApproverAction.

**Comment by samrocketman** [comment]
There's not much I can comment on this as it's out of my area of expertise.  I'll look it over and try to better understand it.

**Comment by jglick** [comment]
What is the goal of this PR? Is there an issue with background information?

**Comment by i386** [comment]
@jglick https://issues.jenkins-ci.org/browse/JENKINS-40672 https://issues.jenkins-ci.org/browse/JENKINS-40926

**Pull request closed without merging**
